apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: userserviceapi-ing
spec:
  ingressClassName: nginx
  rules:
  - host: arch.homework
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: userserviceapi
            port:
              number: 8080