apiVersion: v1
kind: Service
metadata:
  labels:
    app: userserviceapi
  name: userserviceapi-svc
spec:
  ports:
    - name: "http"
      port: 8080
      targetPort: 8080
    - name: "https"
      port: 8081
      targetPort: 8081
  selector:
    app: userserviceapi
