apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.postgres.volumeName }}
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.postgres.volumeStorageCapacity }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"