{
 "title": "UserService.API Metrics Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_request_duration_seconds_bucket[1m])))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{}[1m])) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_request_duration_seconds_bucket[1m])))",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_requests_received_total{}[$__interval])",
     "legendFormat": "{{endpoint}} - {{method}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{code=~\"4..|5..\"}[1m])) by (code)",
     "legendFormat": "{{code}} - {{endpoint}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(system_runtime_cpu_usage[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "npgsql_db_client_connections_usage",
     "legendFormat": "{{pool_name}}"
    }
   ]
  },
  {
   "title": "DB Commands",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(npgsql_db_client_commands_executing[1m])",
     "legendFormat": "Commands executing"
    },
    {
     "expr": "rate(npgsql_db_client_commands_failed[1m])",
     "legendFormat": "Commands failed"
    }
   ]
  }
 ]
}