apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: billingdb-volume-claim
  labels:
    app: billingdb
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi