apiVersion: v1
kind: PersistentVolume
metadata:
  name: billingdb-volume
  labels:
    type: local
    app: billingdb
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"