apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notificationsdb-volume-claim
  labels:
    app: notificationsdb
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi