apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ordersdb-volume-claim
  labels:
    app: ordersdb
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi