apiVersion: v1
kind: Service
metadata:
  labels:
    app: seq
  name: seq
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: api
      protocol: TCP
      port: 5341
      targetPort: 5341
  selector:
    app: seq
