apiVersion: v1
kind: Service
metadata:
  labels:
    app: userservice
  name: userservice
spec:
  type: {{ .Values.userservice.service.type }}
  ports:
    - port: {{ .Values.userservice.service.port }}
      targetPort: {{ .Values.userservice.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: userservice
