apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: usersdb-volume-claim
  labels:
    app: usersdb
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi