apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "userservice.fullname" . }}-ingress
  labels:
    {{- include "userservice.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /seq(/|$)(.*)
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: seq
                port:
                  number: 80
          - path: /api/users(/|$)(.*)
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: userservice
                port:
                  number: 80
          - path: /api(/|$)(.*)
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: apigateway
                port:
                  number: 80
