apiVersion: v1
kind: Service
metadata:
  labels:
    app: billingservice
  name: billingservice
spec:
  type: {{ .Values.billingservice.service.type }}
  ports:
    - port: {{ .Values.billingservice.service.port }}
      targetPort: {{ .Values.billingservice.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: billingservice
