apiVersion: apps/v1
kind: Deployment
metadata:
  name: billingdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billingdb
  template:
    metadata:
      labels:
        app: billingdb
    spec:
      containers:
        - name: billingdb
          image: postgres:17
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: billingdb-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/pgdata
              name: postgresdata
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: billingdb-volume-claim
