apiVersion: v1
kind: Service
metadata:
  labels:
    app: hangfireservice
  name: hangfireservice
spec:
  type: {{ .Values.hangfireservice.service.type }}
  ports:
    - port: {{ .Values.hangfireservice.service.port }}
      targetPort: {{ .Values.hangfireservice.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: hangfireservice
