apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notificationsservice
  name: notificationsservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notificationsservice
  template:
    metadata:
      labels:
        app: notificationsservice
    spec:
      containers:
        - image: {{ .Values.notificationsservice.image.repository }}
          name: notificationsservice
          env:
          - name: PG_CONN_STR
            value: "Host=notificationsdb.default.svc.cluster.local;Port=5432;Database=notifications;Username=pguser;Password=P@ssw0rd"
          - name: SEQ_URL
            value: "http://seq:5341"
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: {{ .Values.notificationsservice.restartPolicy }}
