apiVersion: v1
kind: Service
metadata:
  labels:
    app: notificationsservice
  name: notificationsservice
spec:
  type: {{ .Values.notificationsservice.service.type }}
  ports:
    - port: {{ .Values.notificationsservice.service.port }}
      targetPort: {{ .Values.notificationsservice.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: notificationsservice
