apiVersion: v1
kind: PersistentVolume
metadata:
  name: ordersdb-volume
  labels:
    type: local
    app: ordersdb
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"