apiVersion: v1
kind: Service
metadata:
  labels:
    app: ordersservice
  name: ordersservice
spec:
  type: {{ .Values.ordersservice.service.type }}
  ports:
    - port: {{ .Values.ordersservice.service.port }}
      targetPort: {{ .Values.ordersservice.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: ordersservice
